### ISSUE TITLE
Trouble loading plugins

### ISSUE THREAD

**Issue by ddennetiere** [CEMES-CNRS/pymodaq_plugin_manager#3]
Hi Seb,
i have trouble using the plugins I've installed.
My plugin manager crashes each time I try installing anything. it sends:
```
Fatal Python error: init_sys_streams: can't initialize sys standard streams
ValueError: Cannot open console output buffer for reading
```
 So I've tried installing the plugins with pip and they do show in my lib/site-package folder. But when I try to make a new preset,the dashboard doesn't seem to find the plugins... It should be in the viewer-> add right?

FYI I've reinstalled completely pymodaq 3.1.0 to start with a fresh environment.

Thanks !

**Comment by seb5g** [comment]
similar issue as pymodaq_plugin_manager#2 closing this one
