### ISSUE TITLE
Automate updates for README.md?

### ISSUE THREAD

**Issue by rgeneaux** [CEMES-CNRS/pymodaq_plugin_manager#9]
Right now in the pymodaq documentation, the "list of available plugins" redirects to the readme.md of this repository, which is not necessarily synchronized with pypi. Right now most plugins show the wrong version, for instance, and new ones must be updated by hand.
It means that currently the only way to have a fully updated plugin list is to install the pymodaq_plugin_manager, which is not very practical for potential users who are just looking for info but do not use pymodaq yet.

Perhaps we could use a github workflow to pull the changes from pypi (like pymodaq-plugin-manager does), and automatically update the README.md automatically? And make the workflow trigger every week or something like that.

**Comment by seb5g** [comment]
Hello,
actually I'm doing this from time to time using the validate script in the pymodaq_plugin_manager:
![image](https://user-images.githubusercontent.com/6609955/156788538-0702813d-6976-4c1e-aac6-0b28e705e1ed.png)

then pushing the newly generated (from automatic browsing of pypi) on the repo. For sure, it would be nice if this could be done periodically to reflect new changes on pypi. Could you have a look at this? If yes, I will add you as admin of this repository so you can create the action and test it...
Cheers

**Comment by seb5g** [comment]
#10 solved the issue!
